CONTAINER OSnow {
    INCLUDE Obase;
    NAME OSnow;


    GROUP ID_OBJECTPROPERTIES {

        REAL SNOW_THICKNESS {UNIT PERCENT; CUSTOMGUI REALSLIDER; MIN 50; MAX 1000; STEP 1;}
        REAL SNOW_VIEWPORT { MIN 1; STEP 1;}
        REAL SNOW_RENDER { MIN 1; STEP 1;}

        SEPARATOR { }

        REAL SNOW_POINTS { MIN 25; CUSTOMGUI REALSLIDER; STEP 1; MAXSLIDER 10000;}
        REAL SNOW_POINT_SCALE {UNIT METER; CUSTOMGUI REALSLIDER; MIN 0; STEP 1; MAXSLIDER  25;}
        REAL SNOW_ANGLE {UNIT DEGREE; CUSTOMGUI REALSLIDER; MIN 1; MAX 180; STEP 1;}
        REAL SNOW_SEED {STEP 1;}

    }

}